"use client";
import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { useRouter } from "next/navigation";
import dynamic from "next/dynamic";

const PricesView = dynamic(() => import("./_components/PricesView"), { loading: () => <Spinner /> });
const AgentPriceModal = dynamic(() => import("./_components/AgentPriceModal"));
const AgentPricesAdmin = dynamic(() => import("./_components/AgentPricesAdmin"), { loading: () => <Spinner /> });
const PnLView = dynamic(() => import("./_components/PnLView"), { loading: () => <Spinner /> });
const ApiKeysAdmin = dynamic(() => import("./_components/ApiKeysAdmin"), { loading: () => <Spinner /> });
const AnnouncementsAdmin = dynamic(() => import("./_components/AnnouncementsAdmin"), { loading: () => <Spinner /> });
const PromoBannerAdmin = dynamic(() => import("./_components/PromoBannerAdmin"), { loading: () => <Spinner /> });
const ManualOrdersAdmin = dynamic(() => import("./_components/ManualOrdersAdmin"), { loading: () => <Spinner /> });
const CommissionAdmin = dynamic(() => import("./_components/CommissionAdmin"), { loading: () => <Spinner /> });
const AgentWalletsAdmin = dynamic(() => import("./_components/AgentWalletsAdmin"), { loading: () => <Spinner /> });
const SMSAdmin = dynamic(() => import("./_components/SMSAdmin"), { loading: () => <Spinner /> });
const CustomersAdmin = dynamic(() => import("./_components/CustomersAdmin"), { loading: () => <Spinner /> });
const MashupBundlesAdmin = dynamic(() => import("./_components/MashupBundlesAdmin"), { loading: () => <Spinner /> });
const NetworkProvidersAdmin = dynamic(() => import("./_components/NetworkProvidersAdmin"), { loading: () => <Spinner /> });
const CouponsAdmin = dynamic(() => import("./_components/CouponsAdmin"), { loading: () => <Spinner /> });
const WithdrawalsAdmin = dynamic(() => import("./_components/WithdrawalsAdmin"), { loading: () => <Spinner /> });
const AnalyticsAdmin = dynamic(() => import("./_components/AnalyticsAdmin"), { loading: () => <Spinner /> });
const PaystackSplitAdmin = dynamic(() => import("./_components/PaystackSplitAdmin"), { loading: () => <Spinner /> });